import './terrarium.css'

import React, { Component } from "react";
import { Image } from "antd"
import { Link } from 'react-router-dom';

import portal from '../../images/terrarium/portal.png'
import showcase from '../../images/terrarium/showcase.png'
import notif from '../../images/terrarium/notif.png'
import surrounding from '../../images/terrarium/surrounding.png'
import watering from '../../images/terrarium/watering.png'
import fullGrown from '../../images/terrarium/full-grown.png'
import topView from '../../images/terrarium/top-view.png'
import divider from '../../images/divider.svg'

import preTer1 from '../../images/terrarium/pre-ter-1.png'
import preTer2 from '../../images/terrarium/pre-ter-2.png'
import blenderTer from '../../images/terrarium/blender-ter.png'
import stages from '../../images/terrarium/fern-stages.png'
import nciem from '../../images/terrarium/nciem.png'
import ieee from '../../images/terrarium/ieepaper.png'
import team from '../../images/team.png'

import ProgressBar from "react-scroll-progress-bar";

import Header from '../Header/header';
import Footer from '../Footer/footer';
class Terrarium extends Component {

    componentDidMount() {
        window.scrollTo(0, 0)
      }

    render() {
        return (
            <div>
                <link href="//db.onlinewebfonts.com/c/bb25f84423b9515a1d475d02d2de6462?family=Bell+MT" rel="stylesheet" type="text/css" />
                <link rel="stylesheet" href="https://use.typekit.net/qdb6vxy.css"></link>

                <ProgressBar bgcolor="#303030" duration="2" height="5px" />

                <Header></Header>

                {/* <div className='sticky'><div style={{paddingBottom: "5px"}}>UI Design, UX Research, 3D Modelling</div><hr/></div> */}
                
                <div className='terrarium-banner-container'>
                    <div className='terrarium-banner'>                   
                        <div className="title-ter">Portable Augmented Reality gardening experience</div><br/>
                        <a className="sub-title-ter" href='https://www.researchgate.net/publication/353697031_An_Augmented_Reality_Greenhouse_to_Demonstrate_Game-Based_Learning' target="_blank" rel="noreferrer">
                            <span className="mark">See paper</span>
                        </a>
                    </div>
                </div>


                <div className='banner'>
                    <div className="title">Terrarium - Portable Garden</div>
                    <span style={{padding: "10px", paddingLeft: "0px"}}><img alt='single' src={team} style={{width: "30px"}}></img></span>
                    <span style={{color: "green"}}>College Final Year Group Project</span> 
                    &nbsp; <span style={{color: "grey"}}>August 2020</span>
                </div>

                <div className="things">
                    <br />
                    Augmented Reality is an interactive experience of a real-world environment where the objects that reside in the real world are enhanced by information generated by a computing device. We propose a mobile-based AR application that provides an immersive simulation of a portable plant nurturing experience. The application utilizes the Unity AR Foundation framework to augment a portal to their own virtual garden. The user can explore their garden, build terraria, nurture and maintain various plants, thus providing an end-to-end simulation. This is a novel approach to experimental learning. We explore and evaluate concepts of information absorption, immersion, user satisfaction, and emotional experience by conducting a comparative study between traditional E-learning methodology and E-learning using Augmented Reality.
                    
                    <img src={divider} alt='divider' className='divider' />

                    <div className="sub-heading">Existing System vs Proposed System</div>                                     
                    The traditional pedagogy is not interactive, lacks visual aids, and knowledge transfer can be overwhelming. This makes it difficult to understand concepts if they are not presented correctly. From the point of view of the tutors, this difficulty can cause sharing too much or too little information, nullifying the use of E-learning.
                    Existing AR systems also have their own drawbacks. It is difficult for the AR applications in the existing system to cater to a wide range of age groups and interests. Furthermore, fully immersive existing systems require expensive wearables to simulate the experiences. The proposed system can offer the following advantages:

                    <div className="sub-sub-heading">Interactive and Immersive</div>
                    Actions like watering, seeding, pruning, etc have regular prompts for the user to complete. The intuitive interaction with the application resembles real-world experience and teaches the users the true essence of gardening.


                    <div className="sub-sub-heading">Does not need Demanding Hardware</div>
                    The hardware that my application demands are very minimal. This is done to reach and educate a wide range of audiences. It also does not restrict the user geographically.

                    <div className="sub-sub-heading">Longer Retention and High Reception</div>
                    Since the experience is interactive and hands-on, there is an increase in the information assimilation rate compared to traditional e-learning systems. The learning curve is also short and the retention is more due to visualization of concepts.

                    <div className="sub-sub-heading">Experimental Learning</div>
                    Visualizing precise and interactive 3D models and simulation of the plant growth cycle increases user involvement and immersion. The learning experience is multisensory and lively.

                    <br/><br/>

                    <Image  alt='showcase' src={showcase} width="44vw" />
                    <Image alt='portal' src={portal} width="22vw" />
                    <Image alt='notification' src={notif} width="22vw"/>

                    <Image alt='surrounding' src={surrounding} width="44vw"/>       
                    <img src={divider} alt='divider' className='divider' />
                    
                    <div className="sub-heading">Timeline</div>
                        <div className='sub-sub-heading'>August, 2020</div>
                        The project started during my third year of college (Jan 2020). My mother is a primary school teacher. Since the onslaught of the pandemic, I noticed how difficult it was for her students to understand and learn during class. Learning and Education were going through necessary transformations and I wanted to be at the forefront of it. My two-person team aligned with a project guide who shared similar interests and had valuable experience in emerging technology research. We went through a preliminary screening process by creating small AR Edtech simulations.
                        <br /><br />
                        <Image alt='before terrarium project' src={preTer1} height="44vh" />
                        <Image alt='before terrarium project' src={preTer2} height="44vh" />

                        <div className='sub-sub-heading'>November, 2020</div>
                        We got the opportunity to make the AR product for an EdTech startup called Cambrionics. We created an augmented terrarium where the users could nurture and grow plant species. In my country, smartphones are sometimes a luxury. Hence my team’s main goal was to make the experience as affordable as possible. We wanted to offer an economic experience at the same time not wanting the limit the immersivity. There was a plethora of existing research in Edtech AR. It was exciting and eye-opening for me to research the AR experiences in museums, music lessons, medical schools, pilot training, etc. By assimilating the pain points and the advantages that were concluded in this phase, a clear direction for our research project was formed.
                   
                        <div className='sub-sub-heading'>February, 2021</div>
                        The design and development of the application started in June, 2020. The plant we had chosen for the POC and User Research was ferns. By creating the experience using a familiar plant, the users would be able to grow comfortable with using AR apps. On the design side, I focused on making the fern as realistic as possible. The simulation was decided to have 7 stages of growth with each stage showing a unique and distinguishable aspect of the fern. Apart from that, a transparent container, glass room, watering can, pruning tool, and other cosmetics were modeled. On the development side, my teammate worked on integrating the models in Unity and using REST APIs to trigger interactions
                        <br /><br />
                        <Image alt='blender' src={blenderTer}  />
                        <Image alt='stages of fern' src={stages}  />

                        <div className='sub-sub-heading'>May, 2021</div>
                        We had completed the first round of feasibility studies by May 2021 among our peers. We were then provided with the subjects for user research. With growing excitement, it was time to showcase the application and observe the users. The preparation and evaluation were remotely moderated. The user research consisted of 12 people between the age of 18-25 being divided into 2 groups of 6. A preparation period of 2 hours was given before the evaluation. Group A learned about the fern through a slide deck. Group B used our AR application for the same duration to learn about the plant. The information imparted by both sources was similar, to facilitate a common evaluation system. The survey given to the users consisted of 2 sections. The Assessment section had questions about nurturing ferns and their growth cycle. The Feedback section consisted of evaluating the experience of the users. This included the Experience emotions, user satisfaction, Immersion, and miscellaneous user feedback.
                        
                        <div className='sub-sub-heading'>June, 2021</div>
                        The papers we had meticulously worked on were completed in June 2021. We submitted to the CONIT IEEE conference and the NCIEM conference. During the virtual conferences, it was motivating and rewarding to see the panel not only be impressed by our research but also understand the scope and vision we have for simulating the portable AR experiences in an accessible manner. The paper we submitted for the IEEE conference was also published.
                        <br /><br />
                        <Image alt='nciem' src={nciem}  />
                        <Image alt='ieee' src={ieee} />
                        
                    <img src={divider} alt='divider' className='divider' />

                    <div className="sub-heading">Results</div>
                    <ul>
                        <li>Injecting AR into E-learning has the best information absorption rate. Results have also shown that users of the AR application had a consistent interest in learning compared to users learning from the presentation.</li>

                        <li>Using AR made the users feel more responsible and involved with the life-cycle of the plant when compared to obtaining the information in a more traditional way.</li>

                        <li>The AR portal was a pleasant surprise to users who were familiar with AR. They were impressed by the models of the plants, the greenhouse, and the simulations.</li>
                    </ul>

                    <img src={divider} alt='divider' className='divider' />

                    <div className="sub-heading" >Closer Look</div>
                        <Image src={topView} />
                        <Image src={fullGrown} height="69.5vh" />
                        <Image src={watering} height="69.5vh" />
                        <iframe title='hori ter' src="https://drive.google.com/file/d/1dhk2HiSRhBEZo9f4Jz-hSXP6rDziEkcL/preview" allow="autoplay"></iframe>
                        <iframe title='Terrarium' src="https://drive.google.com/file/d/1zO7E6gntpDsw8ZP4pYNKnIrnWXWk7J1-/preview" allow="autoplay"></iframe>
                    </div>

                    <div className='closerLook'>
                        <br/>
                        <span className='tags'>UI Design</span> 
                        <span className='tags'>3D Modelling</span>    
                        <span className='tags'>UX Research</span> 
                    </div>

                    <br/><br/>
                    <div className='things'>
                        See other projects<br/>
                        <Link className='see-more' style={{color: "magenta"}} to='/casestudy'>Case Study</Link>
                        <Link className='see-more' style={{color: "gold"}} to='/hewandfrost'>Hew and Frost</Link>
                        <Link className='see-more' style={{color: "purple"}} to='/tabs'>Tabs</Link>
                    </div>

                <Footer></Footer>

            </div>
        );
    }
}

export default Terrarium;