import './terrarium.css'

import React, { Component} from "react";
import { Col, Image, Row, Card } from "antd"

import selected from '../../images/terrarium/selected.svg'

import portal from '../../images/terrarium/portal.png'
import showcase from '../../images/terrarium/showcase.png'
import notif from '../../images/terrarium/notif.png'
import surrounding from '../../images/terrarium/surrounding.png'
import watering from '../../images/terrarium/watering.png'
import pruning from '../../images/terrarium/pruning.png'
import fullGrown from '../../images/terrarium/full-grown.png'
import topView from '../../images/terrarium/top-view.png'

import preTer1 from '../../images/terrarium/pre-ter-1.png'
import preTer2 from '../../images/terrarium/pre-ter-2.png'
import blenderTer from '../../images/terrarium/blender-ter.png'
import stages from '../../images/terrarium/fern-stages.png'
import nciem from '../../images/terrarium/nciem.png'
import ieee from '../../images/terrarium/ieepaper.png'
import terBanner from '../../images/terrarium/ter-banner.png'

import result1 from '../../images/terrarium/result1.mp4'
import result2 from '../../images/terrarium/result2.mp4'
import result3 from '../../images/terrarium/result3.mp4'
import terrariumvid from '../../images/terrarium/Terrarium.mp4'
import terrariumvid2 from '../../images/terrarium/terrariumvid2.mp4'

import { Chrono } from "react-chrono";


const { Meta } = Card;

const items = [{ title: "August 2020" }, { title: "November 2020" }, { title: "Feb 2021" }, { title: "May 2021" }, { title: "June 2021" }
]

class terrarium extends Component {


    state = {
        timeLineIcon: selected,

    }


    render() {
        return (
            <div>
                <Col style={{ paddingLeft: "126px" }}>
                    <Row><img src={terBanner} className="ui-img-ter"></img></Row>
                    <Row style={{ width: "700px" }}><div className="title-ter">Portable Agmented Reality gardening experience</div></Row>
                    <Row style={{ width: "700px" }}><div className="sub-title-ter"><span className="mark">See paper</span></div></Row>
                </Col>

                <div className="body-ter">


                    <div className="sub-heading-ter">Abstract</div>
                    <div className="content-ter">Augmented Reality is an interactive experience of a real-world environment where the objects that reside in the real world are enhanced by
                        information generated by a computing device. We propose a mobile-based AR application that provides an immersive simulation of a
                        portable plant nurturing experience. The application utilizes the Unity AR Foundation framework to augment a portal to their own virtual
                        garden. The user is able to explore their garden, build terraria, nurture and maintain various plants, thus providing an end-to-end simulation.
                        This is a novel approach in experimental learning. We explore and evaluate concepts of information absorption, immersivity, user
                        satisfaction and experience emotions by conducting a comparative study between traditional E-learning methodology and E-learning using
                        Augmented Reality.
                    </div>


                    <div className="content-ter">
                        <div className="sub-heading-ter">Existing System vs Proposed System</div>

                            <p>The traditional pedagogy is not interactive, lacks visual aspects, and knowledge transfer can be overwhelming.
                            This makes it difficult to understand concepts if they are not presented correctly. From the point of view of the tutors, this difficulty
                            can cause sharing too much or too little information, nullifying the use of E-learning.<br />
                            On the other hand, existing AR systems also have their own drawbacks. It is difficult for the AR applications in the existing system to
                            cater to a wide range of age groups and interests. Furthermore, fully immersive existing systems require expensive wearables to simulate the experiences.
                            The proposed system can offer the following advatages:</p>
                            <b>Interactive and Immersive</b>
                            <p>Actions like watering, seeding, pruning, etc are regularly prompted for the user to complete. The intuitive interaction with the
                                application resembles real-world experience and teaches the users the true essence of gardening.</p>


                            <b>Does not need Demanding Hardware</b>
                            <p>The hardware that our application demands are very minimal. This is done to reach and educate a wide range of audiences. It also does not restrict the user geographically.</p>

                            <b>Longer Retention and High Reception: </b>
                            <p>Since the experience is interactive and hands-on, there is an increase in the information assimilation rate compared to traditional e-learning systems. Apart from that,
                                the learning curve is also short and the retention is more due to visualization of concepts.</p>

                            <b>Experimental Learning: </b>
                            <p>Visualizing precise and interactive 3D models and simulation of the plant growth cycle increases user involvement and immersion. The learning experience becomes multisensory
                                and lively.</p>
                        
                        <Col >

                            <Row>
                                <Col><div style={{ paddingBottom: "0px" }} className="image"><img src={showcase} height="210px" /></div></Col>
                                <Col><div style={{ paddingBottom: "0px" }} className="image"><img src={portal} width="200px" /></div></Col>
                                <Col><div style={{ paddingBottom: "0px" }} className="image"><img src={notif} width="200px" /></div></Col>
                            </Row>

                            <Row>
                                <Col><div className="image" ><img src={surrounding} width="805px" /></div></Col>
                            </Row>

                        </Col>

                    </div>

                    <div>
                        <div className="sub-heading-ter">Timeline</div>
                        <div>
                            <Chrono mode="VERTICAL" hideControls items={items} borderLessCards theme={{ primary: "#000000", secondary: "rgba(51, 255, 0, 0.7)", titleColor: "black" }}>
                                <div className="content-ter-timeline">The project started during my third year of college. We had to decide on a research topic and procure a project guide.
                                    My mother is a primary school teacher. Since the onslaught of the pandemic, I noticed how difficult it was for students to understand and learn during class. Learning and
                                    Education were going through necessary transformations and I wanted to be at the forefront of it. Thus, the seeds of inspiration to create an Edtech AR system were planted.
                                    My team’s next task was to find a project guide that aligned with our interests. Our faculty put us through a screening process where we had to create small AR EdTech projects.
                                    <br /><br/>
                                    <span><img src={preTer1} width="230px" /></span>
                                    <span style={{ marginLeft: "10px" }}><img src={preTer2} width="300px" /></span></div>

                                <div className="content-ter-timeline">After being selected by our project guide, we tried to narrow down the scope of our research. We got the opportunity
                                    to collaborate with a startup called Cambrionics and see the technology that reached the masses. We zeroed down to create an augmented terrarium where the users could nurture
                                    and grow plant species. Now my team’s next goal was to make the experience as immersive and affordable as possible. There was a plethora of existing research in Edtech AR.
                                    It was exciting and eye-opening for me to research the AR experiences in museums, music lessons, medical schools, pilot training, etc. By assimilating the pain points and the
                                    advantages that were concluded in this research, a clear direction for our research project was formed.</div>

                                <div className="content-ter-timeline">We designed and developed the application in the following months. The plant we had chosen for the POC and User Research
                                    was ferns. I noticed an active community and abundant knowledge of fern gardening. By bringing the experience using a familiar plant, the users would be able to grow comfortable
                                    with using AR. On the design side, I  focused on making the fern as realistic as possible. The simulation was decided to have 7 stages of growth with each stage showing a unique
                                    and distinguishable aspect of the fern. Apart from that, a transparent container, glass room, watering can, pruning tool, and other cosmetics were modeled. On the development
                                    side, my teammate worked on integrating the models in Unity and using REST APIs to trigger interactions.
                                    <br /><br/>
                                    <span><img src={blenderTer} width="700px" /></span>

                                    <span style={{ marginLeft: "10px" }}><img src={stages} width="670px" /></span>
                                </div>
                                <div className="content-ter-timeline">The application for POC was complete. We had completed the first round of feasibility studies among our peers. After working on
                                    their feedback, we were now ready for understanding a wider user base. We were provided with the subjects for user research. With growing excitement, it was time to showcase the application and observe the users.
                                    The preparation and evaluation were remotely moderated. The user research consisted of 12 people between the age of 18-25 being divided into 2 groups of 6. A preparation period of 2 hours was
                                    given before the evaluation. Group A learned about the fern through a slide deck. Group B used our AR application for the same duration to learn about the plant. The
                                    information imparted by both sources was similar, in order to facilitate a common
                                    evaluation system. The survey given to the users consisted of 2 sections. The Assessment
                                    section had questions about nurturing ferns and their growth cycle. The Feedback section
                                    consisted of evaluating the experience of the users. This included the Experience emotions,
                                    user satisfaction, Immersion, and miscellaneous user feedback.
                                </div>

                                <div className="content-ter-timeline">The papers we had meticulously worked on were completed. We prepared our presentations for the conference as well as finished
                                    the final stage of paper submission. We submitted to the CONIT IEEE conference as well as the NCIEM conference. During the virtual conferences, it was motivating and rewarding to see
                                    the panel not only be impressed but also understand the scope and vision we have for implementing portable AR experiences in an accessible way. The paper we submitted for the IEEE
                                    conference was also published.

                                    <br /><br/>
                                    <span><img src={nciem} width="700px" /></span>
                                    <span style={{ marginLeft: "20px" }}><img src={ieee} width="660px" /></span>
                                </div>

                            </Chrono>
                        </div>
                    </div>


                    <div className="sub-heading-ter" style={{paddingTop: "40px"}}>Results</div>
                    <div className="content-ter">
                        <Row >
                            <Col><video src={result1} width="420" style={{}}
                                controls={null}
                                loop={true}
                                muted={true}
                                autoplay="true" /></Col>
                            <Col style={{ width: "420px", margin: "auto", textAlign: "justify", padding: "20px" }}>Injecting AR into E-learning has a better information absorption rate. Results also showed that users of the AR application depicted consistent interest in learning compared to users learning from the presentation.</Col>
                        </Row>

                        <Row>
                            <Col style={{ width: "420px", margin: "auto", textAlign: "justify", padding: "20px", paddingLeft: "0px" }}>Using AR made the users feel more responsible and involved with the life-cycle of the plant when compared to obtaining the information in a more traditional way.</Col>
                            <Col><video src={result2} width="420" style={{}}
                                controls={null}
                                loop={true}
                                muted={true}
                                autoplay="true" /></Col>

                        </Row>

                        <Row>
                            <Col><video src={result3} width="420" style={{}}
                                controls={null}
                                loop={true}
                                muted={true}
                                autoplay="true" /></Col>
                            <Col style={{ width: "420px", margin: "auto", textAlign: "justify", padding: "20px" }}>The AR portal was a pleasant surprise to users who were familiar with AR. They were impressed by the models of the plants, the greenhouse, and the simulations.</Col>
                        </Row>

                    </div>

                    <div className="sub-heading-ter" >Closer Look</div>
                    <div className="content-ter" >
                        <Row>
                            <Col span={15}>
                                <span className="image"><Image src={topView} width="520px" /></span>
                                <span className="image"><Image src={fullGrown} height="210px" /></span>
                                <span className="image"><Image src={watering} height="210px" /></span>
                                <span className="image"><Image src={pruning} height="210px" /></span></Col>
                            <Col><video src={terrariumvid} height="510px" muted={true} controls={true} /></Col>
                        </Row>
                        <Row><video src={terrariumvid2} width="820px" controls={true} muted={true} /></Row>
                    </div>


                </div>
            </div>
        );
    }
}

export default terrarium;